name: Deploy Blazor WASM PWA to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Update Project Structure
        run: |
          echo "Generating comprehensive project structure..."
          
          # Verify project directory structure
          echo "Repository root contents:"
          ls -la
          
          # Navigate to project directory and validate
          if [ -d "AirCode" ]; then
            cd AirCode
            echo "AirCode directory contents:"
            ls -la
          else
            echo "Warning: AirCode directory not found, using repository root"
          fi
          
          # Enhanced structure generation function
          generate_comprehensive_structure() {
            local base_path="$1"
            local output_file="$2"
          
            # Initialize output file with metadata
            {
              echo "Project Structure Documentation"
              echo "Generated: $(date -u)"
              echo "Repository: ${{ github.repository }}"
              echo "Commit: ${{ github.sha }}"
              echo "=================================="
              echo
            } > "$output_file"
          
            # Capture all project-relevant files
            echo "Source Files:" >> "$output_file"
            echo "============" >> "$output_file"
            find "$base_path" -type f \( \
              -name "*.cs" -o \
              -name "*.razor" -o \
              -name "*.csproj" -o \
              -name "*.sln" -o \
              -name "*.json" -o \
              -name "*.css" -o \
              -name "*.scss" -o \
              -name "*.js" -o \
              -name "*.ts" -o \
              -name "*.html" -o \
              -name "*.md" \
            \) -not -path "*/bin/*" \
              -not -path "*/obj/*" \
              -not -path "*/.git/*" \
              -not -path "*/node_modules/*" | \
            sed "s|^$base_path/||" | sort >> "$output_file"
          
            echo >> "$output_file"
            echo "Directory Structure:" >> "$output_file"
            echo "==================" >> "$output_file"
          
            # Generate hierarchical directory tree
            find "$base_path" -type d \
              -not -path "*/bin" \
              -not -path "*/bin/*" \
              -not -path "*/obj" \
              -not -path "*/obj/*" \
              -not -path "*/.git" \
              -not -path "*/.git/*" \
              -not-path "*/node_modules" \
              -not -path "*/node_modules/*" | \
            sed "s|^$base_path||" | \
            sed 's|^/||' | \
            sort | \
            sed 's|[^/]*/|  |g' | \
            sed 's|^|./|' >> "$output_file"
          
            echo >> "$output_file"
            echo "File Count Summary:" >> "$output_file"
            echo "==================" >> "$output_file"
          
            # Generate file type statistics
            for ext in cs razor csproj sln json css js html; do
              count=$(find "$base_path" -name "*.$ext" -not -path "*/bin/*" -not -path "*/obj/*" | wc -l)
              if [ "$count" -gt 0 ]; then
                printf "%-10s: %d files\n" ".$ext" "$count" >> "$output_file"
              fi
            done
          }
          
          # Determine correct base path and output location
          if [ -d "AirCode" ]; then
            # Ensure output directory exists
            mkdir -p "AirCode/Others"
            generate_comprehensive_structure "AirCode" "AirCode/Others/ProjectStructure.txt"
          else
            # Fallback to repository root
            mkdir -p "Others"
            generate_comprehensive_structure "." "Others/ProjectStructure.txt"
          fi
          
          echo "Project structure documentation completed successfully"

      - name: Commit Updated Project Structure
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Determine structure file location
          STRUCTURE_FILE=""
          if [ -f "AirCode/Others/ProjectStructure.txt" ]; then
            STRUCTURE_FILE="AirCode/Others/ProjectStructure.txt"
          elif [ -f "Others/ProjectStructure.txt" ]; then
            STRUCTURE_FILE="Others/ProjectStructure.txt"
          fi
          
          if [ -n "$STRUCTURE_FILE" ]; then
            # Verify changes exist before committing
            if ! git diff --quiet "$STRUCTURE_FILE" 2>/dev/null; then
              git add "$STRUCTURE_FILE"
              git commit -m "Auto-update project structure documentation [skip ci]"
              git push
              echo "Project structure committed successfully"
            else
              echo "No changes detected in project structure"
            fi
          else
            echo "Warning: Project structure file not found"
          fi

      - name: Restore and Build
        working-directory: ./AirCode
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore

      - name: Publish
        working-directory: ./AirCode
        run: dotnet publish --configuration Release --no-build --output ../dist

      - name: Fix PWA Integrity Issues
        run: |
          echo "🔧 Fixing PWA integrity issues for GitHub Pages deployment..."
          
          # Set deployment variables
          REPO_NAME="${{ github.event.repository.name }}"
          SHORT_SHA="${{ github.sha }}"
          SHORT_SHA="${SHORT_SHA:0:8}"
          BASE_PATH="/${REPO_NAME}/"
          
          # Create pages directory
          mkdir -p ./pages
          cp -r ./dist/wwwroot/* ./pages/
          touch ./pages/.nojekyll
          
          # 1. Fix service-worker-assets.js for GitHub Pages paths
          if [ -f "./pages/service-worker-assets.js" ]; then
            echo "📝 Updating service worker assets for GitHub Pages..."
            
            # Update all asset URLs to include the repository path
            sed -i "s|\"url\": \"/|\"url\": \"${BASE_PATH}|g" ./pages/service-worker-assets.js
            
            # Update the service worker URL itself
            sed -i "s|\"url\": \"service-worker.js\"|\"url\": \"${BASE_PATH}service-worker.js\"|g" ./pages/service-worker-assets.js
            
            echo "✅ Service worker assets updated"
          fi
          
          # 2. Fix service-worker.published.js integrity checks
          if [ -f "./pages/service-worker.published.js" ]; then
            echo "🛠️ Fixing service worker integrity checks..."
            
            # Copy and modify the service worker
            cp ./pages/service-worker.published.js ./pages/service-worker.js
            
            # Remove integrity parameter to fix GitHub Pages deployment issues
            sed -i 's|new Request(asset\.url, { integrity: asset\.hash })|new Request(asset.url)|g' ./pages/service-worker.js
            
            # Update cache names and version
            sed -i "s|'AirCode-cache-'|'${REPO_NAME}-cache-'|g" ./pages/service-worker.js
            sed -i "s|cache-v1|cache-v${SHORT_SHA}|g" ./pages/service-worker.js
            
            echo "✅ Service worker integrity checks fixed"
          fi
          
          # 3. Configure PWA manifest for GitHub Pages
          if [ -f "./pages/manifest.json" ]; then
            echo "📱 Configuring PWA manifest..."
            
            # Update start_url and scope for GitHub Pages
            sed -i "s|\"start_url\": \"/\"|\"start_url\": \"${BASE_PATH}\"|g" ./pages/manifest.json
            sed -i "s|\"scope\": \"/\"|\"scope\": \"${BASE_PATH}\"|g" ./pages/manifest.json
            
            # Update icon paths
            sed -i "s|\"src\": \"/|\"src\": \"${BASE_PATH}|g" ./pages/manifest.json
            
            echo "✅ PWA manifest configured"
          fi
          
          # 4. Update index.html for GitHub Pages
          echo "🌐 Configuring index.html for GitHub Pages..."
          
          # Update base href
          sed -i "s|<base href=\"/\" />|<base href=\"${BASE_PATH}\" />|g" ./pages/index.html
          
          # Add SPA routing support script
          sed -i "/<base href=\"[^\"]*\" \/>/a\\    \\n    <!-- SPA routing support for GitHub Pages -->\\n    <script type=\"text/javascript\">\\n        (function(l) {\\n            if (l.search[1] === \"/\" ) {\\n                var decoded = l.search.slice(1).split(\"&\").map(function(s) { \\n                return s.replace(/~and~/g, \"&\")\\n                }).join(\"?\");\\n                window.history.replaceState(null, null,\\n                    l.pathname.slice(0, -1) + decoded + l.hash\\n                );\\n            }\\n        }(window.location))\\n    </script>" ./pages/index.html
          
          echo "✅ Index.html configured"
          
          # 5. Create 404.html for SPA routing
          echo "🔀 Creating SPA routing support..."
          
          cat > ./pages/404.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
            <head>
              <meta charset="utf-8">
              <title>AirCode - Page Not Found</title>
              <script type="text/javascript">
                var pathSegmentsToKeep = 1;
                var l = window.location;
                l.replace(
                  l.protocol + '//' + l.hostname + (l.port ? ':' + l.port : '') +
                  l.pathname.split('/').slice(0, 1 + pathSegmentsToKeep).join('/') + '/?/' +
                  l.pathname.slice(1).split('/').slice(pathSegmentsToKeep).join('/').replace(/&/g, '~and~') +
                  (l.search ? '&' + l.search.slice(1).replace(/&/g, '~and~') : '') +
                  l.hash
                );
              </script>
            </head>
            <body>
              <p>Redirecting to AirCode...</p>
            </body>
          </html>
          EOF
          
          echo "✅ 404.html created"
          
          # 6. Verify and log final structure
          echo "📊 Final PWA structure verification:"
          echo "- Service worker: $([ -f "./pages/service-worker.js" ] && echo "✅" || echo "❌")"
          echo "- Service worker assets: $([ -f "./pages/service-worker-assets.js" ] && echo "✅" || echo "❌")"
          echo "- PWA manifest: $([ -f "./pages/manifest.json" ] && echo "✅" || echo "❌")"
          echo "- SPA routing: $([ -f "./pages/404.html" ] && echo "✅" || echo "❌")"
          echo "- Icons directory: $([ -d "./pages/icons" ] && echo "✅" || echo "❌")"
          
          echo "🚀 PWA deployment preparation completed successfully"

      - name: Upload Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./pages

  deploy:
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
