name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore and Build
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ./dist

      - name: Prepare Pages
        run: |
          mkdir -p ./pages
          cp -r ./dist/wwwroot/* ./pages/
          touch ./pages/.nojekyll
          cp ./pages/index.html ./pages/404.html
          sed -i 's|<base href="/" />|<base href="/${{ github.event.repository.name }}/" />|g' ./pages/index.html ./pages/404.html
          
          # Fix service worker paths
          if [ -f "./pages/service-worker.js" ]; then
            sed -i 's|"/|"/${{ github.event.repository.name }}/|g' ./pages/service-worker.js
          fi
          if [ -f "./pages/service-worker.published.js" ]; then
            sed -i 's|"/|"/${{ github.event.repository.name }}/|g' ./pages/service-worker.published.js
          fi

      - name: Upload Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./pages

  deploy:
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4