name: AirCode Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore and Build
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ./dist

      - name: Prepare Pages
        run: |
          mkdir -p ./pages
          cp -r ./dist/wwwroot/* ./pages/
          touch ./pages/.nojekyll
          
          # Create 404.html that redirects to index.html for SPA routing
          cat > ./pages/404.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <meta charset="utf-8">
              <title>AirCode</title>
              <script>
                  // Redirect to index.html with the current path as a query parameter
                  var path = window.location.pathname.replace('/${{ github.event.repository.name }}', '');
                  window.location.replace('/${{ github.event.repository.name }}/#' + path);
              </script>
          </head>
          <body>
              Redirecting...
          </body>
          </html>
          EOF
          
          # Update base href and favicon paths
          sed -i 's|<base href="/" />|<base href="/${{ github.event.repository.name }}/" />|g' ./pages/index.html
          sed -i 's|href="favicon.png"|href="/${{ github.event.repository.name }}/favicon.png"|g' ./pages/index.html
          sed -i 's|href="manifest.json"|href="/${{ github.event.repository.name }}/manifest.json"|g' ./pages/index.html
          sed -i 's|href="icon-512.png"|href="/${{ github.event.repository.name }}/icon-512.png"|g' ./pages/index.html
          sed -i 's|href="icon-192.png"|href="/${{ github.event.repository.name }}/icon-192.png"|g' ./pages/index.html
          
          # Replace development service worker with production version
          if [ -f "./pages/service-worker.published.js" ]; then
            cp ./pages/service-worker.published.js ./pages/service-worker.js
            sed -i 's|"/|"/${{ github.event.repository.name }}/|g' ./pages/service-worker.js
          fi

      - name: Upload Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./pages

  deploy:
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4